### PR TITLE
updated markdown code syntax, Vundle instructions

### PR DESCRIPTION
**Pull request by wolftune**
I added instructions that a plugin-manager works, changed some headers,
and made the commands clearer via actual markdown code syntax instead of just quotes

### CODE REVIEW

**Comment by bkad** [comment]
Sorry, it's not a markdown file, its a reStructuredText file. If you want to remove the markdown changes and keep the vundle instructions, I can merge this.

**Comment by wolftune** [comment]
@bkad I see, sorry, I was confused. Almost all README files on GitHub use Markdown. Is there no way in .rst to specify a bit of *in-line* code as a literal code bit? It's too easy to miss the commas in around things have the quote marks. The rendering of Markdown puts a different color and a monospace font around literal code bits.

I'd prefer to update the syntax to use .rst version of marking the bits as code, but if that's not possible, I'll resubmit with just the Vundle bit and forget about the other improvements.

**Comment by bkad** [comment]
fixed in b3995f5ee908fa184af877b5da1a0d274af55bb2

**Comment by wolftune** [comment]
Hmm, the update is a little screwy, it has a double back-slash `\\` where I think it meant to be a single `\` and it uses cases of single-quote markup as in `'w'` when it probably should have been ``w`` etc

**Comment by bkad** [comment]
Thanks for the review, I've made some further adjustments in 0bb12f03535828b020ae730cafb7f8b30f8e6e41

**Pull request closed without merging**
