### PR TITLE
Merged in louispan's changes allowing iw to work properly at end of line

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by bkad** [comment]
I think this breaks motion between the end of one line to the next.

**Comment by faceleg** [comment]
Was that motion intentional?

```JavaScript
var aCamelCaseWord|
aCamelCaseWord = hat;
```

`ci,w` (change inside camel case word)

```JavaScript
var aCamelCase
CamelCaseWord = hat;
```

This is unexpected behaviour to me

**Comment by faceleg** [comment]
Related: #17

**Comment by bkad** [comment]
```
var aCamelCase[W]ord
aCamelCaseWord = hat;

<CamelCaseMotion_w>

var aCamelCaseWor[d]
aCamelCaseWord = hat;

<CamelCaseMotion_w>

var aCamelCaseWor[d]
aCamelCaseWord = hat;
```

The 'w' motion didn't move past the first line which is unexpected behavior for me.

**Comment by faceleg** [comment]
True, this breaks `<CamelCaseMotion_w>`'s movement function.

Is there any way we can have the `<CamelCaseMotion_w>` movement and *not* have `ci<CamelCaseMotion_w>` eat the `\n` at the end of a line?

This would match vim's default `w` behaviour.

**Comment by bkad** [comment]
I'm not currently aware of such a solution that has correct behavior for both.

Open to suggestions though :)

**Comment by faceleg** [comment]
No longer use this module.

**Pull request closed without merging**
